Sidebranch
kalviumcommunity/balancebox pull request #4
Opened 2023-03-16 06:37 UTC by chirag4582

![image](https://user-images.githubusercontent.com/115335660/225534742-997f7ddb-ae4a-4408-88b4-47901b22fbe7.png)
hosted backened on render

2023-03-16 06:58 UTC, aditya-190 requested changes
Great work on the changes! However, before we proceed with merging, there are a few issues that need to be addressed. Please take a look at them and make the necessary changes.

2023-03-16 06:58 UTC, aditya-190 commented on backend/.env
Add your `.env` to `.gitignore` file to prevent it from getting pushed ti GitHub as this file generally contains some confidential data that you don't want to expose in public. Also delete this file from GitHub now.

2023-03-16 06:58 UTC, aditya-190 commented on backend/package.json
> +  "name": "backend",
You can rename it to balancebox_backend

2023-03-16 06:58 UTC, aditya-190 commented on backend/routes/auth.js
> +    const data = await Food.find({});
`Food.find({})` can be replaced with `Food.find()` and also it is a good practice to remove all `console.log` before merging the code to production.

2023-03-16 06:58 UTC, aditya-190 commented on client/README.old.md
This file can be deleted.

2023-03-16 06:58 UTC, aditya-190 commented on client/package.json
> +    "mongoose": "^7.0.1",
Could you kindly help me understand why `express-async-handler` and `mongoose` have been added to the frontend? They are typically used in backend.

2023-03-18 04:58 UTC, PatelNeelMahesh requested changes
Implement the changes asked here and push the changes here then merge pull request.

2023-03-22 04:44 UTC, merged